facility_id = 104
court_type = "badminton"
begin_time = "16:30"
end_time = "22:30"
weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Sunday"]

[api]
url = "https://api.tenis4u.pl"
headers = { "x-tenis-user-agent" = "tenis4u-web-frontoffice/3.6.0" }
fetch_interval_minutes = 20
max_proxies_ready = 5