name: Auto Deploy to OCI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'tests/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USERNAME }}
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
            set -e
            cd ~/tenis4uMonitor
            git pull origin main
            
            # Auto-create .env from .env.example
            cp .env.example .env
            sed -i "s|^APP_ENV=.*|APP_ENV=prod|" .env
            sed -i "s|^DEV_API__DISCORD_WEBHOOK_URL=.*|DEV_API__DISCORD_WEBHOOK_URL=${{ secrets.DEV_API__DISCORD_WEBHOOK_URL }}|" .env
            sed -i "s|^PROD_API__DISCORD_WEBHOOK_URL=.*|PROD_API__DISCORD_WEBHOOK_URL=${{ secrets.PROD_API__DISCORD_WEBHOOK_URL }}|" .env
            
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart tenis4uscript.service
